@Host=http://localhost:5400

GET {{Host}}/companies
Accept: application/json

###

GET {{Host}}/companies/1
Accept: application/json

###

POST {{Host}}/companies/
Content-Type: application/json

{
    "Name": "Santa Monica",
    "Description": "Game Developer",
    "Website": "http://www.santamonica.com",
    "Location": "Remote"
}

###

PUT {{Host}}/companies/4
Content-Type: application/json

{
    "Id": 4,
    "Name": "Guerrilla",
    "Description": "Senior Game Developer"
}

###

DELETE {{Host}}/companies/2


// **** Job Applications ****

###

GET {{Host}}/jobapplication
Accept: application/json

###

GET {{Host}}/jobapplication/1
Accept: application/json

###

POST {{Host}}/jobapplication
Content-Type: application/json

{
    "Position": "Junior Game Developer",
    "JobUrl": "https://www.job.com",
    "CompanyId": 4
}

###

PUT {{Host}}/jobapplication/2
Content-Type: application/json

{
    "Position": "Junior Java Developer"
}

###

DELETE {{Host}}/jobapplication/4