@Host=http://localhost:5400

GET {{Host}}/api/companies
Accept: application/json

###

GET {{Host}}/api/companies/1
Accept: application/json

###

POST {{Host}}/api/companies/
Content-Type: application/json

{
    "Name": "Nintendo",
    "Description": "Game Developer",
    "Website": "http://www.naughtydog.com",
    "Location": "Hyrule"
}

###

PUT {{Host}}/api/companies/4
Content-Type: application/json

{
    "Id": 4,
    "Name": "Guerrilla",
    "Description": "Senior Game Developer"
}

###

DELETE {{Host}}/api/companies/2

###

GET {{Host}}/api/companies?jobapplicationposition=game%20developer


// **** Job Applications ****

###

GET {{Host}}/api/applications
Accept: application/json

###

GET {{Host}}/api/applications/1
Accept: application/json

###

POST {{Host}}/api/applications
Content-Type: application/json

{
    "Position": "Game Developer",
    "JobUrl": "https://www.job.com",
    "CompanyId": 6
}

###

PUT {{Host}}/api/applications/2
Content-Type: application/json

{
    "Position": "Junior Java Developer"
}

###

DELETE {{Host}}/api/applications/4

###

GET {{Host}}/api/applications?appliedat=2026-07-07

Accept: application/json

// **** ApplicationNote ***

GET {{Host}}/applicationnote
Accept: application/json

###

GET {{Host}}/applicationnote/1
Accept: application/json

###

POST {{Host}}/applicationnote
Content-Type: application/json

{
    "Content": "No response until now",
    "JobApplicationId": 1
}

###

PUT {{Host}}/applicationnote/1
Content-Type: application/json

{
    "Content": "Received an email, let's see what happens"
}

###

DELETE {{Host}}/applicationnote/2
